# Generated by Django 4.0.4 on 2022-04-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialNetWork', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to='socialNetWork.profile'),
        ),
    ]
