# Generated by Django 4.0.4 on 2022-04-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialNetWork', '0003_post_liked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='liked_by',
            field=models.ManyToManyField(to='socialNetWork.profile'),
        ),
    ]
