# Generated by Django 4.0.4 on 2022-04-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialNetWork', '0006_post_test_alter_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_posts', to='socialNetWork.profile'),
        ),
    ]
