# Generated by Django 4.0.4 on 2022-04-17 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialNetWork', '0007_post_liked_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='liked_by',
            new_name='liked',
        ),
    ]
